export const SHIFT_HOURS = 8;

export const WORKING_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  INCOMPLETE: 'INCOMPLETE'
};

export const VALIDATION_STATUS = {
  PENDING: 'PENDING',
  VALID: 'VALID',
  INVALID: 'INVALID'
};

export const OVERTIME_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};
