export const GEO_STATUS = {
  INSIDE: 'inside_geofence',
  OUTSIDE: 'outside_geofence'
};

export const GEOFENCE_DECISION = {
  ALLOWED: 'ALLOWED',
  BLOCKED: 'BLOCKED',
  MARKED_SUSPICIOUS: 'MARKED_SUSPICIOUS',
  GPS_ACCURACY_FAILED: 'GPS_ACCURACY_FAILED',
  WFH_BYPASS: 'WFH_BYPASS',
  GEOFENCE_DISABLED: 'GEOFENCE_DISABLED'
};

export const GEO_VIOLATION_ACTION = {
  BLOCKED: 'BLOCKED',
  ALLOWED: 'ALLOWED',
  MARKED_SUSPICIOUS: 'MARKED_SUSPICIOUS',
  GPS_ACCURACY_FAILED: 'GPS_ACCURACY_FAILED',
  WFH_BYPASS: 'WFH_BYPASS'
};